version: "3.3"
services:
  yuna:
    image: nginx
    volumes:
      - "./nginx/webroot:/webroot"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    networks:
      - "router_default"
      - "default"
    restart: always

  php:
    build: php
    volumes:
      - "./nginx/webroot:/webroot"
    restart: always
    networks:
      - "default"
      - "production_db_default"

  crawler:
    build: crawler
    networks:
      - "production_db_default"
      - "default"
    restart: always

  payments:
    build: payments
    volumes:
      - "./payments/data/:/srv/data/"
    restart: always

  onion:
    build: onion
    restart: always

networks:
  production_db_default:
    external: true
  router_default:
    external: true
