version: "3.3"
services:
  backend:
    build: backend
#    ports:
#      - "443:443"
    volumes:
      - "./frontend:/frontend/"
      - "./config:/config/"
      - "/etc/letsencrypt:/etc/letsencrypt"
    networks:
      - "production_db_default"
      - "router_default"
      - "default"
    restart: always

  crawler:
    build: crawler
    networks:
      - "production_db_default"
      - "default"
    restart: always

networks:
  default:
  production_db_default:
    external: true
  router_default:
    external: true
